learn_foreign_words/urls.py
from django.conf.urls import url
from views import *

'''
urlpatterns = patterns('',
    url(r'^$', start_page, name='start_page'),
#    url(r'^popular/', question_popular, name='question_popular'),
#    url(r'^question/(?P<q_id>\d+)/', question, name='question'),
#    url(r'^ask/', ask_add, name='ask'),
#    url(r'^answer/', answer_add, name='answer'),
#    url(r'^signup/', signup, name='signup'),    
#    url(r'^login/', my_login, name='my_login'),
)
'''

urlpatterns = [
    url(r'^$', start_page, name='start_page'),
    url(r'^load_file/', load_file, name='load_file'),
    url(r'^dict_status_set/', dict_status_set, name='dict_status_set'),

]

r5am_1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^learn_foreign_words/', include('learn_foreign_words.urls')),
    url(r'^vhfdx_fd_locators/', include('vhfdx_fd_locators.urls')),
]

learn_foreign_words/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

__author__ = 'Aleksandr Jashhuk, Zoer, R5AM, www.r5am.ru'


# Типы словарей
class ReferenceDictType(models.Model):
    dict_type = models.CharField(max_length=50,
                                 verbose_name='Тип словаря',
                                 unique=False,
                                 default='basic')

    class Meta:
        verbose_name = 'Тип словаря'
        verbose_name_plural = 'Типы словарей'

    def __unicode__(self):
        return self.dict_type or u''


# Основной словарь
class Dictionary(models.Model):
    foreign_word = models.CharField(max_length=100,
                                    verbose_name='Иностранное слово',
                                    unique=False)
    translate_word = models.CharField(max_length=255,
                                      verbose_name='Перевод слова')
    dict_type = models.ForeignKey(ReferenceDictType)

    class Meta:
        ordering = ['foreign_word']
        verbose_name = 'Иностранное слово'
        verbose_name_plural = 'Иностранные слова'

    def __unicode__(self):
        return self.foreign_word or u''

    def get_url(self):
        return reverse('dictionary', kwargs={'id': self.id})


# Статусы словарей
class GlobalStatus(models.Model):
    basic_dict_status = models.BooleanField(default=False)
    user_dict_status = models.BooleanField(default=False)
    swodesh_dict_status = models.BooleanField(default=False)
    cw_dict_status = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Состояние'
        verbose_name_plural = 'Состояния'

    def __unicode__(self):
        return self.basic_dict_status or u''

    # Выдает статусы словарей
    @staticmethod
    def get_status(self):
        return {'basic_dict': self.basic_dict_status,
                'user_dict': self.user_dict_status,
                'swodesh_dict': self.swodesh_dict_status,
                'cw_dict': self.cw_dict_status}

    # Изменяет статусы словарей
    @staticmethod
    def set_status(self, status):
        self.basic_dict_status = status['basic_dict']
        self.user_dict_status = status['user_dict']
        self.swodesh_dict_status = status['swodesh_dict']
        self.cw_dict_status = status['cw_dict']
        self.save()

        return None

learn_foreign_words/forms.py
# -*- coding: utf-8 -*-
from django import forms

__author__ = 'Aleksandr Jashhuk, Zoer, R5AM'


class TranslateWordForm(forms.Form):
    translate_word = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(TranslateWordForm, self).__init__(*args, **kwargs)
        self.fields['translate_word'].widget.attrs.update({'autofocus': 'true',
                                                           'required': 'required',
                                                           'placeholder': 'введите перевод слова'})

    def clean_translate_word(self):
        translate_word = self.cleaned_data['translate_word']
        if translate_word.strip() == '':
            raise forms.ValidationError(u'Поле не заполнено.')
        return translate_word


class LoadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    my_file = forms.FileField(label='Свой словарь')

    # def clean_load_file_form(self):
    #     my_file = self.cleaned_data['my_file']
    #     if my_file.name == '':
    #         raise forms.ValidationError(u'Поле не заполнено')
    #     return my_file

learn_foreign_words/views.py
# -*- coding: utf-8 -*-
from __future__ import print_function
from django.shortcuts import render
from learn_foreign_words.logic.logic_learn_foreign_words import get_random_word, \
                                                                correctness_translate, \
                                                                handle_loaded_file, \
                                                                clear_dictionary
from learn_foreign_words.logic.zoer_ajax import HttpResponseAjax
from models import Dictionary, GlobalStatus
from forms import TranslateWordForm, LoadFileForm
from django.views.decorators.cache import never_cache
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt

__author__ = 'Aleksandr Jashhuk, Zoer, R5AM, www.r5am.ru'

random_word_global = ''
random_word_global_2 = ''


@require_http_methods(['GET', 'POST'])
@never_cache
def start_page(request):
    global random_word_global
    global random_word_global_2
    context = ''

    if request.method == 'POST':
        template = 'result_page.html'
        form = TranslateWordForm(request.POST)

        # Считываем с какими словарями работать
        dict_status = GlobalStatus.objects.get(id=1)
        dict_status_db = GlobalStatus.get_status(dict_status)
        # print(dict_status_db)

        if form.is_valid():
            entered_word = form.cleaned_data['translate_word']
            result = correctness_translate(entered_word, random_word_global)
            context = {
                    'random_word': random_word_global_2,
                    'entered_word': entered_word,
                    'random_word_global': random_word_global,
                    'result': result,
                    'basic_dict_status': dict_status_db['basic_dict'],
                    'user_dict_status': dict_status_db['user_dict'],
                    'swodesh_dict_status': dict_status_db['swodesh_dict'],
                    'cw_dict_status': dict_status_db['cw_dict'],
            }
    else:   # GET
        template = 'start_page.html'
        form = TranslateWordForm()

        # Считываем с какими словарями работать
        dict_status = GlobalStatus.objects.get(id=1)
        dict_status_db = GlobalStatus.get_status(dict_status)
        # print(dict_status_db)

        all_words = Dictionary.objects.all()

        # Выбираем слова из активных словарей
        if dict_status_db['basic_dict'] is False:
            all_words = all_words.exclude(dict_type=1)
        if dict_status_db['cw_dict'] is False:
            all_words = all_words.exclude(dict_type=2)
        if dict_status_db['swodesh_dict'] is False:
            all_words = all_words.exclude(dict_type=3)
        if dict_status_db['user_dict'] is False:
            all_words = all_words.exclude(dict_type=4)

        # Получаем случайное иностранное слово
        random_word = get_random_word(all_words)
        random_word_global = random_word.translate_word
        random_word_global_2 = random_word.foreign_word
        context = {
                    'random_word': random_word,
                    'form': form,
                    'basic_dict_status': dict_status_db['basic_dict'],
                    'user_dict_status': dict_status_db['user_dict'],
                    'swodesh_dict_status': dict_status_db['swodesh_dict'],
                    'cw_dict_status': dict_status_db['cw_dict'],
        }
    return render(request, template, context)


@require_http_methods(['GET', 'POST'])
def load_file(request):
    template = 'load_file_page.html'

    if request.method == 'POST':
        form = LoadFileForm(request.POST, request.FILES)
        context = {'form': form, }
        if form.is_valid():
            result_load_file = handle_loaded_file(request.FILES['my_file'])
            if result_load_file == '':
                template = 'successful_load_file.html'
            else:
                template = 'bad_load_file.html'
                context = {'file_error': result_load_file}
    else:   # GET
        # Очистка словаря пользователя
        clear_dictionary(Dictionary)

        form = LoadFileForm()
        context = {'form': form, }

    return render(request, template, context)


@require_http_methods(['POST'])
@csrf_exempt
def dict_status_set(request):

    # Считываем с какими словарями работали
    dict_status = GlobalStatus.objects.get(id=1)
    status_in_db = GlobalStatus.get_status(dict_status)

    for status_list in ['basic_dict', 'cw_dict', 'swodesh_dict', 'user_dict']:
        status = (request.POST.get(status_list))
        if status == 'on':
            status_in_db[status_list] = True     # Изменяем статус словаря
        elif status == 'off':
            status_in_db[status_list] = False

    # Высталяем статусы словарей в БД
    GlobalStatus.set_status(dict_status, status_in_db)

    return HttpResponseAjax()

learn_foreign_words/templates/about_modal.html
{# Модальное окно   #}
    <div id="aboutModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div id="headerModal" class="modal-header">
                        О программе
                </div>
                <div class="modal-body">
                    Эта программа предназначена для запоминания иностранных слов.
                    <br><br>
                    Хочется ещё сделать:<br>
                     - Вывод статистики правильных/неправильных переводов.<br>
                </div>
                <div class="modal-footer">
                    <button type="button"
                            class="btn btn-success btn-lg"
                            data-dismiss="modal">
                                OK
                    </button>
                </div>
            </div>
        </div>
    </div>

learn_foreign_words/templates/bad_load_file.html
{% extends "base_page.html" %}

{% block title %}
    {{ block.super }} Загрузка файла.
{% endblock %}

{% block content %}
    <h4>Файл загрузить не удалось!</h4>
    <pre>{{ file_error }}</pre>
    <br><br>
    <a id="btn-ok" href="/learn_foreign_words/" class="btn btn-success btn-block">
        Дальше
    </a>
{% endblock %}

learn_foreign_words/templates/base_page.html
<!doctype html>
<html lang="ru">
    {% load staticfiles %}
<head>
    <title>
        {% block title %}Запоминатель иностранных слов.{% endblock %}
    </title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'learn_foreign_words/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'learn_foreign_words/css/apps.css' %}">
</head>

<body>
	<h2>Запоминатель иностранных слов</h2>
    <a href="//www.r5am.ru">&nbsp;R5AM.RU&nbsp;</a>
    <div class="row">
        <div id="base" class="col-sm-12 col-md-12">
            {% block content %}{% endblock %}
        </div>
    </div>

    <div class="row div-footer">
        <div class="footer col-sm-12 col-md-12">

            <label id="label_basic_dict" class="btn btn-info btn-footer">
                Основной словарь
                <span class="dictCheckbox">
                    <input type="checkbox" value="1" id="checkbox_basic_dict" name="">
                    <label for="checkbox_basic_dict"></label>
                </span>
            </label>

            <label id="label_cw_dict" class="btn btn-info btn-footer">
                Словарь CW слов
                <span class="dictCheckbox">
                    <input type="checkbox" value="1" id="checkbox_cw_dict" name="">
                    <label for="checkbox_cw_dict"></label>
                </span>
            </label>

            <label id="label_swodesh_dict" class="btn btn-info btn-footer">
                Словарь Сводеша
                <span class="dictCheckbox">
                    <input type="checkbox" value="1" id="checkbox_swodesh_dict" name="">
                    <label for="checkbox_swodesh_dict"></label>
                </span>
            </label>

            <label id="label_user_dict" class="btn btn-info btn-footer">
                Cловарь пользователя
                <span class="dictCheckbox">
                    <input type="checkbox" value="1" id="checkbox_user_dict" name="">
                    <label for="checkbox_user_dict"></label>
                </span>
            </label>
        </div>
    </div>


    <div class="row div-footer">
        <div class="footer col-sm-12 col-md-12">
            <a class="btn btn-info btn-footer"
               data-toggle="modal"
               data-target="#aboutModal">
                    О программе
            </a>
            <a id="load-file-btn"
               class="btn btn-info btn-footer"
               href="/learn_foreign_words/load_file/">
                    Загрузить словарь пользователя
            </a>
        </div>
    </div>
    {% include 'about_modal.html' %}
    <script type="text/javascript"
            src="{% static 'learn_foreign_words/js/jquery.min.js' %}">
    </script>
    <script type="text/javascript"
            src="{% static 'learn_foreign_words/js/bootstrap-modal.js' %}">
    </script>
    <script type="text/javascript">
        {# Изменение состояния чекбоксов на странице и занесение статусов словарей в БД #}
        $(document).ready(function(){
            $("#checkbox_basic_dict").click(function(){
                if($(this).is(':checked')){
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {basic_dict: 'on'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('Используется базовый словарь.')}
                    }).error(function () {alert('Ошибка: Базовый словарь не подключился!')} )
                } else {
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {basic_dict: 'off'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('Базовый словарь отключен.')}
                    }).error(function () {alert('Ошибка: Базовый словарь не отключился!')} )
                }
            });

            $("#checkbox_cw_dict").click(function(){
                if($(this).is(':checked')){
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {cw_dict: 'on'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('Используется CW словарь.')}
                    }).error(function () {alert('Ошибка: CW словарь не подключился!')} )
                } else {
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {cw_dict: 'off'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('CW словарь отключен.')}
                    }).error(function () {alert('Ошибка: CW словарь не отключился!')} )
                }
            });

            $("#checkbox_swodesh_dict").click(function(){
                if($(this).is(':checked')){
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {swodesh_dict: 'on'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('Используется словарь Сводеша.')}
                    }).error(function () {alert('Ошибка: Словарь Сводеша не подключился!')} )
                } else {
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {swodesh_dict: 'off'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('Словарь Сводеша отключен.')}
                    }).error(function () {alert('Ошибка: Словарь Сводеша не отключился!')} )
                }
            });

            $("#checkbox_user_dict").click(function(){
                if($(this).is(':checked')){
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {user_dict: 'on'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('Используется словарь пользователя.')}
                    }).error(function () {alert('Ошибка: Словарь пользователя не подключился!')} )
                } else {
                    $.ajax({
                        url: '/learn_foreign_words/dict_status_set/', type: 'POST',
                        data: {user_dict: 'off'}
                    }).success(function (data) {
                        if(data.status == 'ok') {alert('Словарь пользователя отключен.')}
                    }).error(function () {alert('Ошибка: Словарь пользователя не отключился!')} )
                }
            });
        });

        {# Запуск скриптов из start_page.html после загрузки base_page.html #}
        start_page();

    </script>
</body>
</html>

learn_foreign_words/templates/load_file_page.html
{% extends "base_page.html" %}

{% block title %}
    {{ block.super }} Загрузка файла.
{% endblock %}

{% block content %}
    <form action="/learn_foreign_words/load_file/"
          enctype="multipart/form-data"
          method="post">
        {% csrf_token %}
        <h5>Словарь пользователя:</h5>
        <input id="id_my_file" name="my_file" type="file">
        <br>
        <input id="btn-ok" class="btn btn-success btn-block"
               type="submit" value="Загрузить">
    </form>
{% endblock %}

learn_foreign_words/templates/result_page.html
{% extends "base_page.html" %}

{% block title %}
    {{ block.super }} Страница результата.
{% endblock %}

{% block content %}
    <h1>{{ random_word }}</h1>
    <h2>{{ entered_word }}</h2>
        {% if result %}
            <h3 id="estimation">Верно</h3>
            <br><br>
        {% else %}
            <h4 id="estimation">Ошибка</h4>
            <h5>{{ random_word_global }}</h5>
        {% endif %}
        <br>
        {# На form не переделывать - кешировать начинает!!! #}
        <a id="btn-ok" href="/learn_foreign_words/"
                       class="btn btn-success btn-block">
            Дальше
        </a>

{#    {{ basic_dict_status }}#}
{#    {{ cw_dict_status }}#}
{#    {{ swodesh_dict_status }}#}
{#    {{ user_dict_status }}#}

     {# Выставление чекбоксов на странице по данным из таблицы статусов словарей #}
    <script type="text/javascript">
        {# TODO: Отрефакторить в цикл без повторов IF-ов. #}
        function start_page() {
            {% if basic_dict_status == True %}
{#                alert('Установка чеккед для basic_dict.');#}
                $("#checkbox_basic_dict").prop("checked", true);
            {% else %}
{#                alert('Сброс чеккед для basic_dict.');#}
                $("#checkbox_basic_dict").prop("checked", false);
            {% endif %}

            {% if cw_dict_status == True %}
                $("#checkbox_cw_dict").prop("checked", true);
            {% else %}
                $("#checkbox_cw_dict").prop("checked", false);
            {% endif %}

            {% if swodesh_dict_status == True %}
                $("#checkbox_swodesh_dict").prop("checked", true);
            {% else %}
                $("#checkbox_swodesh_dict").prop("checked", false);
            {% endif %}

            {% if user_dict_status == True %}
                $("#checkbox_user_dict").prop("checked", true);
            {% else %}
                $("#checkbox_user_dict").prop("checked", false);
            {% endif %}
        }
    </script>

{% endblock %}

learn_foreign_words/templates/start_page.html
{% extends "base_page.html" %}

{% block title %}
    {{ block.super }} Стартовая страница.
{% endblock %}

{% block content %}
    <h1>{{ random_word.foreign_word }}</h1>

    {% for e in form.non_field_errors %}
        <div>{{ e }}</div>
    {% endfor %}

    <form method="post" action="/learn_foreign_words/">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field }}
            <br>
        {% endfor %}
        <br>
        <p>
            <button id="btn-ok" type="submit" class="btn btn-success btn-block">
                OK
            </button>
    </form>

{#    {{ basic_dict_status }}#}
{#    {{ cw_dict_status }}#}
{#    {{ swodesh_dict_status }}#}
{#    {{ user_dict_status }}#}

 {# Выставление чекбоксов на странице по данным из таблицы статусов словарей #}
    <script type="text/javascript">
        {# TODO: Отрефакторить в цикл без повторов IF-ов. #}
        function start_page() {
            {% if basic_dict_status == True %}
{#                alert('Установка чеккед для basic_dict.');#}
                $("#checkbox_basic_dict").prop("checked", true);
            {% else %}
{#                alert('Сброс чеккед для basic_dict.');#}
                $("#checkbox_basic_dict").prop("checked", false);
            {% endif %}

            {% if cw_dict_status == True %}
                $("#checkbox_cw_dict").prop("checked", true);
            {% else %}
                $("#checkbox_cw_dict").prop("checked", false);
            {% endif %}

            {% if swodesh_dict_status == True %}
                $("#checkbox_swodesh_dict").prop("checked", true);
            {% else %}
                $("#checkbox_swodesh_dict").prop("checked", false);
            {% endif %}

            {% if user_dict_status == True %}
                $("#checkbox_user_dict").prop("checked", true);
            {% else %}
                $("#checkbox_user_dict").prop("checked", false);
            {% endif %}
        }
    </script>
{% endblock %}

learn_foreign_words/templates/success_load_file.html
{% extends "base_page.html" %}

{% block title %}
    {{ block.super }} Страница загрузки файла.
{% endblock %}

{% block content %}
    <h3>Файл успешно загружен</h3>
    <br><br><br>
    <a href="/learn_foreign_words/"
       class="btn btn-success btn-block"
       style="font-size: 5rem">
            Дальше
    </a>
{% endblock %}

learn_foreign_words/templates/successful_load_file.html
{% extends "base_page.html" %}

{% block title %}
    {{ block.super }} Загрузка файла.
{% endblock %}

{% block content %}
    <h3>Файл успешно загружен</h3>
    <br><br><br>
    <a id="btn-ok" href="/learn_foreign_words/"
                   class="btn btn-success btn-block">
        Дальше
    </a>
{% endblock %}